import type { Metadata } from "next";
import "./globals.css";
import { Lora } from "next/font/google";
import { cookies } from "next/headers";

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin", "cyrillic", "cyrillic-ext"],
});

// export const metadata: Metadata = {
//   title: "Naharhana.com hoş geldiňiz!",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const Cookie = await cookies();
  const locale = Cookie.get("NEXT_LOCALE")?.value || "tk";
  return (
    <html lang={locale}>
      <body className={`${lora.variable} antialiased`}>{children}</body>
    </html>
  );
}
